### ISSUE TITLE
Quotient should be graceful to 404 payloads, as the inexistent .well-known case shows

### ISSUE THREAD

**Issue by ognarb** [quotient-im/libQuotient#421] opened 2020-12-17 12:49 UTC
### Description

Quotient::Connections::resolveServer doesn't work when .well-know is not correctly configured.
This means that when using this method on a server that doesn't support the .well-know
specification, it won't work, but according to the source code, it is intended too: https://github.com/quotient-im/libQuotient/blob/master/lib/connection.cpp#L296

This is how I use this method in NeoChat: https://invent.kde.org/network/neochat/-/blob/master/src/controller.cpp#L111 

Unfortunately, I don't have access to any server without .well-know and for the moment I told my NeoChat users with these sort of servers to just configure their .well-know file as workaround :D   

Triggering this issue as low priority.

**Comment by KitsuneRal** [comment] 2020-12-17 13:23
Right, a completely missing .well-known file should not prevent Quotient from resolving a server. It's actually very easy to check - just point to an existing web (non-Matrix) server that returns 404 on non-existing files (not 403 - that's important). That also may be the reason why your clients report the issue - if their Matrix servers return 403 on trying to reach the non-existent .well-known resource, Quotient will just stop resolving (the spec allows to just stop in that case although it also provisions that a user may be asked to confirm connecting in this case; unfortunately, it's not quite possible to support triggering such confirmation atm).

On the other hand, the code in Neochat is now overdoing it - just calling `loginWithPassword()` should be enough to both resolve the server and login. That won't help with 403 though, just an optimisation.

**Comment by KitsuneRal** [comment] 2020-12-17 13:25
(Just checked: the current code sets `google.com` for a base server URL if you try to resolve `@anyone:google.com`.)

**Comment by Modelmat** [comment] 2020-12-23 00:27
I believe the issue here (at least for me), is that `d->resolverJob->status()` is returning 
```
quotient.jobs: "GetWellknownJob" status IncorrectResponse: illegal value
```
, which allows it to pass through [this line](https://github.com/quotient-im/libQuotient/blob/42b78ce6c487d6c39415f160de1bf0f9aaa12185/lib/connection.cpp#L273)
```cpp
if (d->resolverJob->status() != BaseJob::NotFoundError) {
```
where it gets caught by the first if-statement and `returns` out of the function.

Further up in the logs I can see:
```
quotient.jobs.sync: 200 <- GET https://kde.modular.im/_matrix/client/r0/sync
quotient.jobs.sync: Sent GET https://kde.modular.im/_matrix/client/r0/sync
quotient.jobs: Sent GET https://google.com:443/.well-known/matrix/client
quotient.jobs: 404 <- GET https://google.com:443/.well-known/matrix/client
quotient.jobs: "GetWellknownJob" status NotFoundError: Error transferring https://google.com:443/.well-known/matrix/client - server replied: Not Found
```
which indicates at some point there is a `NotFoundError`, but this isn't what is being given to the lambda.

**Comment by KitsuneRal** [comment] 2020-12-23 12:40
The retries occur because the status is `IncorrectResponse`, rather than `NotFound`. Would be great to better understand what exactly that "incorrect response" look like. Any chance to run NeoChat under the debugger? Alternatively, if the server allows public connections you can just send the serverpart to me (if you don't want to put it here, you can send it in private to `@kitsune:matrix.org` in Matrix) and I'll check it out myself.

**Comment by Modelmat** [comment] 2020-12-23 13:30
I would be able to send after Christmas.

But this is reproducible with just `google.com` as a server, (and also `eggy.cc` is another matrix server I quickly found without well-known).

**Comment by KitsuneRal** [comment] 2020-12-23 13:37
Oh ok - I looked the wrong way, you're right, I can see it even with google.com - thanks for patience :)

**Closed** 2020-12-23 16:29 UTC
Labels: bug
